"""Single source of truth for product and artifact version metadata."""

APP_VERSION = '7.5.0'
PRODUCT_SERIES = 'V7.5'
PRODUCT_DISPLAY_NAME = f'JARVIS AI OMEGA {PRODUCT_SERIES}'
WINDOWS_ARTIFACT_BASENAME = f'JARVIS-OMEGA-{PRODUCT_SERIES}'
WINDOWS_INSTALLER_BASENAME = f'JARVIS-AI-OMEGA-{PRODUCT_SERIES}-Setup'
